language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.6.5
install:
    - pip install Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt --use-mirrors
script:
    - python runtests.py
